package com.javaproject.gui;

import com.javaproject.boltshare.Client;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author rudra
 */
public class ClientPage extends javax.swing.JFrame {

    private final HashMap<String, String> clientInformation = new HashMap();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DesiredPeerID;
    private javax.swing.JTextField DirectoryPath;
    private javax.swing.JTextField FileName;
    private javax.swing.JButton FirstEnter;
    private javax.swing.JTextField PeerID;
    private javax.swing.JTextField RePortNumber;
    private javax.swing.JButton SecondEnter;
    private javax.swing.JButton ThirdButton;
    private javax.swing.JButton FourthButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField peerServerPort;
    Client client = new Client();
    private ArrayList<String> listOfFiles;
    /**
     * Creates new form ClientServer
     */
    public ClientPage() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientPage().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PeerID = new javax.swing.JTextField();
        peerServerPort = new javax.swing.JTextField();
        DirectoryPath = new javax.swing.JTextField();
        FileName = new javax.swing.JTextField();
        RePortNumber = new javax.swing.JTextField();
        DesiredPeerID = new javax.swing.JTextField();
        FirstEnter = new javax.swing.JButton();
        SecondEnter = new javax.swing.JButton();
        ThirdButton = new javax.swing.JButton();
        FourthButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTextField2.setText("jTextField1");

        jLabel4.setText("Enter the directory path that contains the file:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(37, 27, 55));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BOLT SHARE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(22, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(33, 158, 188));
        jPanel2.setForeground(new java.awt.Color(33, 158, 188));

        PeerID.setBackground(new java.awt.Color(37, 27, 55));
        PeerID.setForeground(new java.awt.Color(255, 255, 255));
        PeerID.setText("Peer ID");

        peerServerPort.setBackground(new java.awt.Color(37, 27, 55));
        peerServerPort.setForeground(new java.awt.Color(255, 255, 255));
        peerServerPort.setText("Port Number");

        DirectoryPath.setBackground(new java.awt.Color(37, 27, 55));
        DirectoryPath.setForeground(new java.awt.Color(255, 255, 255));
        DirectoryPath.setText("Directory Path");
        DirectoryPath.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                DirectoryPathActionPerformed(evt);
            }
        });

        FileName.setBackground(new java.awt.Color(37, 27, 55));
        FileName.setForeground(new java.awt.Color(255, 255, 255));
        FileName.setText("File Name");

        RePortNumber.setBackground(new java.awt.Color(37, 27, 55));
        RePortNumber.setForeground(new java.awt.Color(255, 255, 255));
        RePortNumber.setText("Re-enter Port Number");

        DesiredPeerID.setBackground(new java.awt.Color(37, 27, 55));
        DesiredPeerID.setForeground(new java.awt.Color(255, 255, 255));
        DesiredPeerID.setText("Desired Peer ID");

        FirstEnter.setBackground(new java.awt.Color(37, 27, 55));
        FirstEnter.setForeground(new java.awt.Color(255, 183, 3));
        FirstEnter.setText("Enter");
        FirstEnter.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                FirstEnterActionPerformed(evt);
            }
        });

        SecondEnter.setBackground(new java.awt.Color(37, 27, 55));
        SecondEnter.setForeground(new java.awt.Color(255, 183, 3));
        SecondEnter.setText("Enter");
        SecondEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondEnterActionPerformed(evt);
            }
        });

        ThirdButton.setBackground(new java.awt.Color(37, 27, 55));
        ThirdButton.setForeground(new java.awt.Color(255, 183, 3));
        ThirdButton.setText("Enter");
        ThirdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirdButtonActionPerformed(evt);
            }
        });

        FourthButton.setBackground(new java.awt.Color(37, 27, 55));
        FourthButton.setForeground(new java.awt.Color(255, 183, 3));
        FourthButton.setText("Enter");
        FourthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    FourthButtonActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                } catch (ClassNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 27, 55));
        jLabel2.setText("CLIENT");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter the directory path that contains the file:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter the port number:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enter the file name:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter the Peer ID:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Re-enter the port number:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter desired Peer ID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(PeerID, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(SecondEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(DirectoryPath)
                                                                .addComponent(peerServerPort))
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(FileName, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(ThirdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(DesiredPeerID, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(RePortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(218, 218, 218)
                                                .addComponent(FirstEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(211, 211, 211)
                                                .addComponent(FourthButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(210, 210, 210)
                                                .addComponent(jLabel2)))
                                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DirectoryPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(peerServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FirstEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(PeerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SecondEnter))
                                .addGap(15, 15, 15)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ThirdButton)
                                        .addComponent(FileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RePortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DesiredPeerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(FourthButton)
                                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DirectoryPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectoryPathActionPerformed

    }//GEN-LAST:event_DirectoryPathActionPerformed

    private void FirstEnterActionPerformed(ActionEvent evt) {//GEN-FIRST:event_FirstEnterActionPerformed
        try {
            clientInformation.put("directoryPath", DirectoryPath.getText());
            clientInformation.put("portNumber", peerServerPort.getText());
            JOptionPane.showMessageDialog(null, "Please enter the Peer Id");

        } catch (HeadlessException ex) {
            //Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FirstEnterActionPerformed

    private void SecondEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondEnterActionPerformed

        clientInformation.put("peerID", PeerID.getText());
        JOptionPane.showMessageDialog(null, "peerID");

    }//GEN-LAST:event_SecondEnterActionPerformed

    private void ThirdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThirdButtonActionPerformed
        clientInformation.put("fileName", FileName.getText());
        ClientInformation clientInformationClass = new ClientInformation(
                clientInformation.get("directoryPath"), clientInformation.get("portNumber"),
                clientInformation.get("peerID"), clientInformation.get("fileName"));
        listOfFiles = client.getClientInformation(clientInformationClass);

        String output = "";
        for(String lof : listOfFiles){
            output += " " + lof + " ";
        }
        JOptionPane.showMessageDialog(null, "List of Files : " + output);

    }//GEN-LAST:event_ThirdButtonActionPerformed

    private void FourthButtonActionPerformed(java.awt.event.ActionEvent evt) throws IOException, ClassNotFoundException {//GEN-FIRST:event_FourthButtonActionPerformed
        client.transferFile(RePortNumber.getText(),DesiredPeerID.getText(),
                clientInformation.get("fileName"),  clientInformation.get("directoryPath"));
        JOptionPane.showMessageDialog(null, "Desired File Successfully Transferred");
    }//GEN-LAST:event_FourthButtonActionPerformed
    // End of variables declaration//GEN-END:variables


}
