package com.javaproject.gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author rudra
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    DBConnection conn;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel Contentpanel;
    private JPanel LoginPanel;
    private JLabel Loginlabel;
    private JLabel pass;
    private JPasswordField passfield;
    private JLabel registerlink;
    private JButton submit;
    private JLabel uname;
    private JTextField unametf;
    public Login() {
        initComponents();
        conn = new DBConnection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new JPanel();
        Loginlabel = new JLabel();
        Contentpanel = new JPanel();
        uname = new JLabel();
        pass = new JLabel();
        submit = new JButton();
        unametf = new JTextField();
        passfield = new JPasswordField();
        registerlink = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(500, 500));

        LoginPanel.setBackground(new Color(3, 7, 30));

        Loginlabel.setBackground(new Color(255, 255, 255));
        Loginlabel.setFont(new Font("Segoe UI", 0, 36)); // NOI18N
        Loginlabel.setForeground(new Color(255, 255, 255));
        Loginlabel.setText("LOGIN PAGE");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
                LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(Loginlabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
                LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(Loginlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(29, Short.MAX_VALUE))
        );

        Contentpanel.setBackground(new java.awt.Color(33, 158, 188));
        Contentpanel.setPreferredSize(new java.awt.Dimension(0, 400));

        uname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 255, 255));
        uname.setText("USERNAME");

        pass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("PASSWORD");

        submit.setBackground(new java.awt.Color(3, 7, 30));
        submit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 183, 3));
        submit.setText("LOGIN");
        submit.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        unametf.setBackground(new java.awt.Color(0, 0, 0));
        unametf.setForeground(new java.awt.Color(255, 255, 255));

        passfield.setBackground(new java.awt.Color(0, 0, 0));
        passfield.setForeground(new java.awt.Color(255, 255, 255));
        passfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passfieldActionPerformed(evt);
            }
        });

        registerlink.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        registerlink.setForeground(new java.awt.Color(3, 7, 30));
        registerlink.setText("click here to Create a new account");
        registerlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerlinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ContentpanelLayout = new javax.swing.GroupLayout(Contentpanel);
        Contentpanel.setLayout(ContentpanelLayout);
        ContentpanelLayout.setHorizontalGroup(
                ContentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ContentpanelLayout.createSequentialGroup()
                                .addGroup(ContentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ContentpanelLayout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addGroup(ContentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(uname)
                                                        .addComponent(pass))
                                                .addGap(58, 58, 58)
                                                .addGroup(ContentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(unametf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(ContentpanelLayout.createSequentialGroup()
                                                .addGap(120, 120, 120)
                                                .addComponent(registerlink))
                                        .addGroup(ContentpanelLayout.createSequentialGroup()
                                                .addGap(179, 179, 179)
                                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(92, Short.MAX_VALUE))
        );
        ContentpanelLayout.setVerticalGroup(
                ContentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ContentpanelLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(ContentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(uname)
                                        .addComponent(unametf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(ContentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pass)
                                        .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(registerlink, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Contentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Contentpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passfieldActionPerformed

    private void submitActionPerformed(ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        PreparedStatement ps;
        ResultSet rs;
        String usname = unametf.getText();
        String uspass = String.valueOf(passfield.getPassword());

        String query = "SELECT *FROM account WHERE username = ? AND password = ?";

        try {
            ps = DBConnection.getConnection().prepareStatement(query);
            ps.setString(1, usname);
            ps.setString(2, uspass);

            rs = ps.executeQuery();

            if (rs.next()) {
                Details det = new Details();
                det.setVisible(true);
                det.pack();
                det.setLocationRelativeTo(null);
                det.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);

            } else {
                JOptionPane.showMessageDialog(null, "Username/Password does not exist");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void registerlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerlinkMouseClicked
        Register reg = new Register();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);

    }//GEN-LAST:event_registerlinkMouseClicked

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked

    }//GEN-LAST:event_submitMouseClicked
    // End of variables declaration//GEN-END:variables

}


